import React from 'react';
import { FileText, Download, FolderPlus, Archive, X, FileSpreadsheet, FileJson, Image as ImageIcon } from 'lucide-react';
import { ScriptOutputFile, downloadSingleFile, downloadFilesAsZip } from '../../lib/output-file-handler';

interface FileOutputModalProps {
  files: ScriptOutputFile[];
  isOpen: boolean;
  onClose: () => void;
  onAddToWorkspaceRoot: (file: ScriptOutputFile) => void;
}

export const FileOutputModal: React.FC<FileOutputModalProps> = ({
  files,
  isOpen,
  onClose,
  onAddToWorkspaceRoot
}) => {
  if (!isOpen || files.length === 0) return null;

  const isMultiple = files.length > 1;

  const handleDownloadSingle = () => {
    if (files[0]) {
      downloadSingleFile(files[0].name, files[0].content);
      onClose();
    }
  };

  const handleDownloadZip = async () => {
    await downloadFilesAsZip(files, 'script_output_files.zip');
    onClose();
  };

  const handleAddToWorkspace = () => {
    if (files[0]) {
      onAddToWorkspaceRoot(files[0]);
      onClose();
    }
  };

  const getFileIcon = (filename: string) => {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    if (ext === 'csv') return <FileSpreadsheet className="h-5 w-5 text-emerald-400 shrink-0" />;
    if (ext === 'json') return <FileJson className="h-5 w-5 text-amber-400 shrink-0" />;
    if (['png', 'jpg', 'jpeg', 'gif', 'svg'].includes(ext)) return <ImageIcon className="h-5 w-5 text-blue-400 shrink-0" />;
    return <FileText className="h-5 w-5 text-primary shrink-0" />;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-xs p-4 animate-in fade-in duration-200">
      <div 
        className="w-full max-w-md rounded-2xl border border-border/80 bg-card p-5 shadow-2xl space-y-4 font-sans relative overflow-hidden animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Glow Header Accent */}
        <div className="absolute -top-12 -left-12 w-32 h-32 bg-primary/20 rounded-full blur-2xl pointer-events-none" />

        {/* Modal Header */}
        <div className="flex items-start justify-between gap-3 relative z-10">
          <div className="flex items-center gap-2.5">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15 border border-primary/30 text-primary shrink-0">
              {isMultiple ? <Archive className="h-5 w-5" /> : <FileText className="h-5 w-5" />}
            </div>
            <div>
              <h3 className="text-base font-bold text-foreground tracking-tight flex items-center gap-1.5">
                {isMultiple ? 'Multiple Output Files Generated' : 'Script Output File Ready'}
              </h3>
              <p className="text-xs text-muted-foreground">
                {isMultiple ? `${files.length} files produced by execution` : '1 output file generated by script'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-muted-foreground hover:bg-muted hover:text-foreground transition-colors cursor-pointer"
            title="Close prompt"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* File Details / Preview Card */}
        <div className="rounded-xl border border-border/60 bg-muted/40 p-3 space-y-2 relative z-10">
          {!isMultiple ? (
            /* Single File Card */
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2.5 min-w-0 flex-1">
                {getFileIcon(files[0].name)}
                <div className="min-w-0 flex-1">
                  <div className="text-xs font-bold font-mono text-foreground truncate">
                    {files[0].name}
                  </div>
                  <div className="text-[10px] text-muted-foreground font-mono">
                    {files[0].path !== files[0].name && <span className="mr-2">Path: {files[0].path}</span>}
                    {files[0].sizeBytes !== undefined && <span>Size: {files[0].sizeBytes} bytes</span>}
                  </div>
                </div>
              </div>
              <span className="rounded bg-emerald-500/10 text-emerald-400 px-2 py-0.5 text-[10px] font-mono font-medium border border-emerald-500/20 shrink-0">
                Ready
              </span>
            </div>
          ) : (
            /* Multiple Files List */
            <div className="space-y-1.5">
              <div className="text-[11px] font-semibold text-muted-foreground flex items-center justify-between">
                <span>Output File Manifest:</span>
                <span className="font-mono text-primary font-bold">{files.length} Files</span>
              </div>
              <div className="max-h-36 overflow-y-auto space-y-1 pr-1 custom-scrollbar">
                {files.map((file, idx) => (
                  <div key={idx} className="flex items-center justify-between gap-2 p-1.5 rounded-lg bg-background/60 border border-border/40 text-xs">
                    <div className="flex items-center gap-2 min-w-0 flex-1">
                      {getFileIcon(file.name)}
                      <span className="font-mono font-medium text-foreground truncate">{file.name}</span>
                    </div>
                    {file.sizeBytes !== undefined && (
                      <span className="text-[10px] font-mono text-muted-foreground shrink-0">{file.sizeBytes} B</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Explanatory Prompt Text */}
        <p className="text-xs text-muted-foreground leading-relaxed relative z-10">
          {!isMultiple
            ? 'The script generated an output file. Would you like to drop it into your workspace root directory or download it directly?'
            : 'The script generated multiple output files. You can download all files packaged into a single .zip archive.'}
        </p>

        {/* Action Buttons */}
        <div className="space-y-2 pt-1 relative z-10">
          {!isMultiple ? (
            /* Single File Options: Drop in Workspace OR Download */
            <div className="grid grid-cols-2 gap-2">
              <button
                onClick={handleAddToWorkspace}
                className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-primary/30 bg-primary/10 px-3 py-2.5 text-xs font-bold text-primary hover:bg-primary/20 transition-all cursor-pointer shadow-xs active:scale-95"
              >
                <FolderPlus className="h-4 w-4 shrink-0" />
                <span>Drop in Workspace</span>
              </button>
              <button
                onClick={handleDownloadSingle}
                className="inline-flex items-center justify-center gap-1.5 rounded-xl bg-primary px-3 py-2.5 text-xs font-bold text-primary-foreground hover:bg-primary/90 transition-all cursor-pointer shadow-sm active:scale-95"
              >
                <Download className="h-4 w-4 shrink-0" />
                <span>Download File</span>
              </button>
            </div>
          ) : (
            /* Multiple Files Option: Download ZIP */
            <button
              onClick={handleDownloadZip}
              className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground shadow-sm hover:bg-primary/90 transition-all cursor-pointer active:scale-95"
            >
              <Archive className="h-4 w-4 shrink-0" />
              <span>Download All as ZIP Archive (.zip)</span>
            </button>
          )}

          <button
            onClick={onClose}
            className="w-full rounded-xl border border-border/60 bg-muted/30 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-muted transition-all cursor-pointer"
          >
            Dismiss
          </button>
        </div>
      </div>
    </div>
  );
};
